services:
  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=${USER_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${USER_SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${USER_SPRING_DATASOURCE_PASSWORD}

  user-db:
    image: postgres
    environment:
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "5432:5432"

  product-service:
    build: ./product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    depends_on:
      - product-db
    environment:
      - SPRING_DATASOURCE_URL=${PRODUCT_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${PRODUCT_SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PRODUCT_SPRING_DATASOURCE_PASSWORD}

  product-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PRODUCT_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "27017:27017"

  order-service:
    build: ./order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=${ORDER_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${ORDER_SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ORDER_SPRING_DATASOURCE_PASSWORD}

  order-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ORDER_DB_NAME}
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Expose port 80 for reverse proxy
    depends_on:
      - user-service
      - product-service
      - order-service
