name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushing to main (after merging PRs)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push user-service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Build and push product-service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./product-service
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

    - name: Build and push order-service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-service
        docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest
